#!/usr/bin/env uv run python
"""Extract verbatim passages from session assessment files.

Deterministic: extracts passages by exact line ranges.
Output: markdown blockquotes with source attribution.
"""

import sys
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent.parent  # repo root

passages = {
    "session-22to23-from-other-assessment.md": [
        # Turn 2: Three actionable insights distilled from AI ergonomics
        {
            "label": "Three actionable insights from AI ergonomics canvas",
            "start_line": 70,
            "end_line": 107,
        },
        # Turn 3: Precision upgrade proposal with exact prompt wording
        {
            "label": "Precision upgrade proposal with exact prompt wording",
            "start_line": 108,
            "end_line": 136,
        },
        # Turn 4: Three targeted prompt changes + user expectation calibration
        {
            "label": "Three targeted prompt changes and user expectation calibration",
            "start_line": 137,
            "end_line": 173,
        },
        # Turn 5: Two-axis convergence with 70% split assessment
        {
            "label": "Two-axis convergence: prompt quality vs split strategy",
            "start_line": 174,
            "end_line": 193,
        },
    ],
    "session-22to23-original-assessment.md": [
        # Broken test set diagnosis
        {
            "label": "Broken test set diagnosis — all three sessions identical",
            "start_line": 145,
            "end_line": 155,
        },
        # Scale inconsistency discovery
        {
            "label": "Scale inconsistency: old evaluation used 0-10, rubric defines 1-5",
            "start_line": 703,
            "end_line": 712,
        },
        # User quality critique
        {
            "label": "User critique: building precision systems while being imprecise",
            "start_line": 820,
            "end_line": 855,
        },
    ],
}


def extract_passages():
    """Extract and format verbatim passages."""
    output_lines = []
    output_lines.append("# Verbatim Session Excerpts\n")
    output_lines.append(
        "> Deterministic extractions from session assessments.\n"
        "> Each passage is quoted verbatim with source attribution.\n"
        "> Generated by `agent/scripts/extract_session_passages.py`.\n"
    )
    output_lines.append("")

    for filename, file_passages in passages.items():
        src_path = BASE / filename
        if not src_path.exists():
            print(f"WARNING: {src_path} not found, skipping", file=sys.stderr)
            continue

        lines = src_path.read_text().splitlines()
        output_lines.append(f"## Source: `{filename}`\n")

        for p in file_passages:
            start = p["start_line"] - 1  # 0-indexed
            end = p["end_line"]  # exclusive
            passage_lines = lines[start:end]

            # Clean up leading/trailing blank lines
            while passage_lines and not passage_lines[0].strip():
                passage_lines.pop(0)
            while passage_lines and not passage_lines[-1].strip():
                passage_lines.pop()

            output_lines.append(f"### {p['label']}\n")
            output_lines.append("> " + "\n> ".join(passage_lines))
            output_lines.append(
                f"\n_Source: `{filename}`, lines {p['start_line']}–{p['end_line']}_\n"
            )

        output_lines.append("")

    return "\n".join(output_lines)


if __name__ == "__main__":
    output = extract_passages()
    out_path = BASE / "docs" / "session-excerpts.md"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(output + "\n")
    print(f"Wrote {out_path}")
    print(f"Passages extracted: {sum(len(v) for v in passages.values())}")